name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - run: npm ci
      - run: npm test
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/

  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ success() && github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: coverage
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Cache Gatsby Cache Folder
        uses: actions/cache@v1
        with:
          path: .cache
          key: ${{ runner.os }}-cache-gatsby
          restore-keys: ${{ runner.os }}-cache-gatsby

      - name: Cache Gatsby Public Folder
        uses: actions/cache@v1
        with:
          path: public/
          key: ${{ runner.os }}-public-gatsby
          restore-keys: ${{ runner.os }}-public-gatsby

      - run: npm ci
      - run: npm run build
        env:
          GATSBY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GATSBY_TYPEKIT_ID: ${{ secrets.GATSBY_TYPEKIT_ID }}
          GATSBY_MAPBOX_ACCESS_TOKEN: ${{ secrets.GATSBY_MAPBOX_ACCESS_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: public
          path: public

  deploy:
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: public
      - run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
